### PR TITLE
Feat: add rollout addon

### PR DESCRIPTION
**Pull request by barnettZQG**
Signed-off-by: barnettZQG <barnett.zqg@gmail.com>

### Description of your changes

Add rollout addon, it provides basic batch publishing capability.

### CODE REVIEW

**Review by wangyikewxgm — DISMISSED** [review]
LGTM

**Review by wonderflow — COMMENTED** [review]
rollout should be in the formal addon instead of experimental

**Comment by barnettZQG** [comment]
> rollout should be in the formal addon instead of experimental

after release 1.2.4, I will move it to the formal addon list.

**Comment by wonderflow** [comment]
> > rollout should be in the formal addon instead of experimental
> 
> after release 1.2.4, I will move it to the formal addon list.

why wait for that?

**Review by wonderflow — CHANGES_REQUESTED** [review]
let‘s move to experimental

**Review by wonderflow — APPROVED** [review]

**Review by wangyikewxgm — APPROVED** [review]

**Pull request merged**
