### PR TITLE
Feat: Argocd addon helm support

### LINKED ISSUE #314: Argocd addon should not  rely on fluxcd
Our argocd addon should be an option for user to delivery helm application. So argocd should not dependent on fluxcd itself.

### PR DESCRIPTION
**Pull request by cezhang**
Signed-off-by: cezhang <c1zhang.dev@gmail.com>

### Description of your changes
- argocd-based helm support
- upgrade argocd to v2.3.3
- rewrite argocd-project and argocd-app with well comment

Fixes #314

### How has this code been tested?
- create normal vela application of helm source
- enable addon initialed by helm source

### Checklist

I have:

- [x] Title of the PR starts with type (e.g. `[Addon]` or `[Trait]`).
- [x] Updated/Added any relevant [documentation] and [examples].
- [x] Unit/E2E Tests added.

### CODE REVIEW

**Comment by wonderflow** [comment]
After this PR merged , can we replace fluxcd by using argcd as the dependency of other addons without any spec change?

**Comment by cezhang** [comment]
> After this PR merged , can we replace fluxcd by using argcd as the dependency of other addons without any spec change?

Yes, except changing the dependency in "metadata.yaml".

**Review by wangyikewxgm — APPROVED** [review]
Great works!LGTM

**Review by wonderflow — APPROVED** [review]
thanks, great job

**Pull request merged**
