### PR TITLE
add a new addon for kubevela-io offline to deploy

### PR DESCRIPTION
**Pull request by oeular**
Signed-off-by: Xueliang Yang <yangxueliang@cmbchina.com>

### Checklist

I have:

- [ ] Title of the PR starts with type (e.g. `[Addon]` or `[Trait]`).
- [ ] Updated/Added any relevant [documentation] and [examples].
- [ ] Unit/E2E Tests added.

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]
good job!

**Comment by zzxwill** [comment]
@oeular Is the addon targeted for those who don't have internet and need to look up KubeVela docs?

**Comment by barnettZQG** [comment]
@oeular It should be noted that there are remote resources such as images in the document.

**Comment by oeular** [comment]
@zzxwill Yeah， The reason for it is special for those who don't have internet（such as us）, and there are also other companies （state-owned enterprises or internet-controlled companies ）facing the same problem.

**Comment by oeular** [comment]
@barnettZQG  Good Tips. I will add more detail info in the readme.md.

**Pull request closed without merging**
